checkpoint_path: /home/akeijser/checkpoints_metriclearning
save: True
comparisons_file: /home/akeijser/MagnaTagATune/comparisons_final.csv
clips_dir: /home/akeijser/MagnaTagATune/mp3
stft_dir: /home/akeijser/MagnaTagATune/stft
verbose: True
validate_every: 10
lr: 0.01
sr: 22050
n_folds: 10
tensorboard_logdir: /home/akeijser/tensorboard_runs
debugging: False

lr_patience: 1
lr_decrease_factor: 0.5


batch_size: 1
valid_batch_size: 1
n_epochs: 1
