checkpoint_path: /home/akeijser/checkpoints_metriclearning
best_checkpoint: best_model_17_May_13_09_32.pt.tar
save: False
comparisons_file: /home/akeijser/MagnaTagATune/comparisons_final.csv
clips_dir: /home/akeijser/MagnaTagATune/mp3
stft_dir: None
verbose: True
validate_every: 10
lr: 0.01
sr: 22050
n_folds: 10
tensorboard_logdir: /home/akeijser/tensorboard_runs
debugging: False

lr_patience: 1
lr_decrease_factor: 0.5


batch_size: 1
valid_batch_size: 1
n_epochs: 50
