checkpoint_path: ./checkpoints_metriclearning
best_checkpoint: best_model_17_May_13_09_32.pt.tar
save: True
comparisons_file: /Users/Alexander/Desktop/music_metriclearning/MagnaTagATune/comparisons_final.csv
clips_dir: /Users/Alexander/Desktop/music_metriclearning/MagnaTagATune/mp3
stft_dir: None
verbose: True
validate_every: 10
lr: 0.01
sr: 22050
n_folds: 10
tensorboard_logdir: ./tensorboard_logs
debugging: True

lr_patience: 1
lr_decrease_factor: 0.5


batch_size: 1
valid_batch_size: 1
n_epochs: 50