checkpoint_path: /Users/Alexander/Desktop/deepthought/checkpoints
save: False
comparisons_file: /Users/Alexander/Desktop/music_metriclearning/MagnaTagATune/comparisons_final.csv
clips_dir: /Users/Alexander/Desktop/music_metriclearning/MagnaTagATune/mp3
stft_dir: /Users/Alexander/Desktop/music_metriclearning/MagnaTagATune/stft
verbose: True
validate_every: 10
lr: 0.01
sr: 22050
n_folds: 10
tensorboard_logdir: ./tensorboard_logs
debugging: False

lr_patience: 1
lr_decrease_factor: 0.5


batch_size: 1
valid_batch_size: 1
n_epochs: 50