name: mus_ml
dependencies:
- python=3.7
- pip
- numpy
- networkx
- pandas
- pyyaml
- pymongo
- pytest
- pytorch
- pip:
    - librosa
    - dsdtools
    - musdb
    - mir-eval
    - sacred
    - torchaudio
